export const HTTP_ERROR = 'GET_ERRORS';

export const AUTH_SET_USER = 'AUTH_SET_USER';

export const POST_CREATED = 'POST_CREATED';
export const POSTS_FETCHED = 'POSTS_FETCHED';
export const POSTS_FEED_FETCHED = 'POSTS_FEED_FETCHED';

export const TOAST_CREATE = 'TOAST_CREATE';
export const TOAST_REMOVE = 'TOAST_REMOVE';

export const FRIEND_ADD = 'FRIEND_ADD';
export const FRIEND_ACCEPTED = 'FRIEND_ACCEPTED';
export const FRIEND_REMOVE = 'FRIEND_REMOVE';
export const FRIEND_FETCHED = 'FRIEND_FETCHED';
