export const HTTP_ERROR = 'GET_ERRORS';

export const AUTH_SET_USER = 'AUTH_SET_USER';

export const POST_CREATED = 'POST_CREATED';
export const POSTS_FETCHED = 'POSTS_FETCHED';
export const POSTS_FEED_FETCHED = 'POSTS_FEED_FETCHED';
export const POSTS_FEED_ADDED = 'POSTS_FEED_ADDED';

export const TOAST_CREATE = 'TOAST_CREATE';
export const TOAST_REMOVE = 'TOAST_REMOVE';

export const FRIEND_ADD = 'FRIEND_ADD';
export const FRIEND_ACCEPTED = 'FRIEND_ACCEPTED';
export const FRIEND_REMOVE = 'FRIEND_REMOVE';
export const FRIEND_FETCHED = 'FRIEND_FETCHED';

export const FRIEND_CONNECTED = 'FRIEND_CONNECTED';
export const FRIEND_DISCONNECTED = 'FRIEND_DISCONNECTED';

export const CHAT_OPENED = 'CHAT_OPENED';
export const CHAT_CLOSED = 'CHAT_CLOSED';
export const CHAT_MESSAGES_FETCHED = 'CHAT_MESSAGES_FETCHED';
export const CHAT_MESSAGE_POSTED = 'CHAT_MESSAGE_POSTED';

export const EDIT_USER = 'EDIT_USER';
